name: Update RSS

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: "0 */8 * * *"
    - cron: "0 20 * * *"
    - cron: "0 22 * * *"

jobs:
  update_rss_feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Install Playwright browsers
        run: npx playwright install chromium
        
      - name: Build project
        run: npm run build
        
      - name: Run scraper
        run: npm start
        
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update RSS feeds'
