name: Update RSS

on:
  pull_request:
  push:
    branches:
    - main
  schedule:
    - cron: "0 */8 * * *"
    - cron: "0 20 * * *"
    - cron: "0 22 * * *"

jobs:
  update_rss_feeds:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - name: Install dependencies
        run: go install cmd/goprimegaming.go
      - name: Run goprimegaming
        run: cd docs && goprimegaming
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
